### PR TITLE
Update language.h to add OneUp/TwoUp ID info

### PR DESCRIPTION
**Pull request by jjwagner**
Not tested yet.

### CODE REVIEW

**Comment by KeithJRome** [comment]
Is there a place where we can introduce a build number too? Something we would increment each time a meaningful change is made to the source?

**Comment by jjwagner** [comment]
The MSG_M115_REPORT #define has "FIRMWARE_NAME:Marlin V1" hard-coded into it for all languages. I debated changing this to "Up-Marlin 1.0", but I don't know if that's considered impolite.

Then again, the new URL points to Up-Marlin, which is pretty clearly a Marlin fork. So maybe it's not a big deal?

**Comment by jjwagner** [comment]
Whoops. Closed by accident.

**Comment by KeithJRome** [comment]
Yeah, I don't think it would be a problem to modify that. It could always say something like "Up V1 (Marlin derivative)"

**Comment by jjwagner** [comment]
I moved the version number to a #define at the top, so that future version changes won't require changing a bunch of lines. 

This flashes and reads back correctly on my Printrboard.

**Comment by KeithJRome** [comment]
Awesome, thanks Jim!

**Pull request merged**
