### PR TITLE
Adding support for red printrbaord

### PR DESCRIPTION
**Pull request by drdelaney**
Adding a block to define black/red printrboard selections for newer qubd
*up units.

### CODE REVIEW

**Comment by ralphxyz** [comment]
Why?

**Comment by drdelaney** [comment]
1. In the event someone comes along some forum posts and sees reference to this, and has a red printrboard, and is not aware of any changes needed, now they can just make a quick change in the configuration.h file and go on their merry way.
2. My little contribution to everyone who has unofficially helped me with problems, tweaks, or hints.
3. Because, I was lucky or unlucky (however you want to look at it) enough to get a red printrboard, from qubd and needed to make the change anyways for myself.
4. Asking "Why?" without a reason behind the question is simply why we cannot have nice things.

**Comment by KeithJRome** [comment]
I'm not familiar with the red boards - are all kits shipping with these now? Or is it a mix of black boards and red boards?

I'm wondering if it might be less confusing to have the red board firmware as an additional (separate) fork (or branch) instead of requiring people to edit the code file if they are "unlucky" and get the non-default board. We could then link to both from the forum post that sends people here (i.e. "click this link if you have a black board, or this other link if you have a red board").

**Comment by drdelaney** [comment]
I believe this is a new shipped board.  As noted in a recent kickstarter post, and a recent RMA from them returning a black board, getting a red one.
The changes are really insignificant. Splitting the firmware would be, in my eyes, a waste of time.

Kickstarter update: https://www.kickstarter.com/projects/qu-bd/qu-bd-one-up-open-source-production-ready-3d-print/posts/945484

forum post about changes here: http://www.fabric8r.com/forums/showthread.php?2055-Red-Printrboard-firmware

**Comment by KeithJRome** [comment]
I see. Can you increment the reported firmware version (I think this was in language.h), and add it to the pull request? I'll merge it once the version is updated.

**Comment by drdelaney** [comment]
Version changed.  Sorry about the commit, revert, then extra commit, silly notepad added extra characters.

**Comment by KeithJRome** [comment]
Good enough :) You can actually clean those commits up without having to add revert mess to the lineage (amending a commit), but it doesn't matter for this repository. On some of the bigger projects they get a little more picky about it.

**Comment by KeithJRome** [comment]
Thanks for the contribution by the way :)

**Pull request merged**
